### PR TITLE
change qwerty pics

### PR DESCRIPTION
**Pull request by ANaka**
new images

image
image
image
image
image
image

### CODE REVIEW

**Comment by charlesfrye** [comment]
thanks for the contribution! testing them now

**Comment by charlesfrye** [comment]
Test cases, from a model trained on "a photo of Qwerty the Golden Retriever".

LGTM.

#  `Qwerty the Golden Retriever`
image

# `a painting of Qwerty The Golden Retriever With A Pearl Earring, by Vermeer`
image

took a few generations to get that, and still not quite as good as it used to be

# `Qwerty the Golden Retriever flying through space as an astronaut`
image

# `low polygon count art of Qwerty the Golden Retriever from the Nintendo 64 game Qwerty The Golden Retriever 64`

image


I see some issues here and in my testing -- less fidelity to the instance, less influence from the prompts -- but they may have to do with the class name change.

**Comment by ANaka** [comment]
>I see some issues here and in my testing -- less fidelity to the instance, less influence from the prompts -- but they may have to do with the class name change.

Happy to contribute a larger training set if and when prior preservation is implemented

Thinking back on some of the artefacts we saw in the outputs - my suspicion is that I saw non-qwerty aspects of this image showing up frequently e.g. bars in the background, outputs being very prone to wearing vests/harnesses, top of head clipped
image

Would not be surprising to me if the output changes a lot based on this - it's so few images to try to train on. It might be fun to think about creating a benchmark of prompts and doing some experiments changing the textual inversion training set to see how the outputs are affected.

**Comment by ANaka** [comment]
image

also this is so good

**Pull request merged**
